"""change table_name

Revision ID: 562da3603f04
Revises: 
Create Date: 2024-10-14 16:38:39.833162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '562da3603f04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lib_books_id', table_name='lib_books')
    op.drop_table('lib_books')
    op.drop_index('ix_books_id', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('author_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('issue_status', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.create_table('lib_books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('author_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('issue_status', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_lib_books_id', 'lib_books', ['id'], unique=False)
    # ### end Alembic commands ###
